import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/header";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400","500","600", "700"], // You can specify the weights you need
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${poppins.className} bg-gradient-to-b from-[#444b1e] to-black`}>
      <body 
        className="bg-gradient-grid bg-[length:40px_40px] min-h-screen  relative"
      > 
        <Header/>
        {children}
      </body>
    </html>
  );
}
